apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app
  name: app
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil-playground

